"""Añadir tablas producto y color_producto

Revision ID: 5fb4dfdc33ab
Revises: d5940ad5c5fb
Create Date: 2025-01-02 13:33:09.145822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb4dfdc33ab'
down_revision = 'd5940ad5c5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('tipoUsuario', sa.Enum('ADMIN', 'EMPLEADO', name='tipousuario'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color_producto.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca_producto.id'], ),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('usuarios')
    op.drop_table('color_producto')
    # ### end Alembic commands ###
