"""0001 Creación de Base de Datos

Revision ID: bf84bda7273d
Revises: 
Create Date: 2024-12-23 12:31:45.437980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf84bda7273d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('tipo_producto_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marca_producto')
    op.drop_table('tipo_producto')
    # ### end Alembic commands ###
